language: node_js
node_js:
  - "7"
cache: yarn
sudo: false
addons:
  code_climate:
    repo_token: 5d31667729cd93bd9ed92cdd1255f40289e7863a79b4566bdaaf1a2978bc0cab
after_success:
  - node_modules/.bin/codeclimate-test-reporter  < coverage/lcov.info
